//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Room : ICSSoft.STORMNET.DataObject
    {
        
        private int fId;
        
        private IIS.Test2.Здание fЗдание;
        
        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Room.Id CustomAttributes)

        // *** End programmer edit section *** (Room.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Room.Id Get start)

                // *** End programmer edit section *** (Room.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Room.Id Get end)

                // *** End programmer edit section *** (Room.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Id Set start)

                // *** End programmer edit section *** (Room.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Room.Id Set end)

                // *** End programmer edit section *** (Room.Id Set end)
            }
        }
        
        /// <summary>
        /// Room.
        /// </summary>
        // *** Start programmer edit section *** (Room.Здание CustomAttributes)

        // *** End programmer edit section *** (Room.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.Test2.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (Room.Здание Get start)

                // *** End programmer edit section *** (Room.Здание Get start)
                IIS.Test2.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (Room.Здание Get end)

                // *** End programmer edit section *** (Room.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Здание Set start)

                // *** End programmer edit section *** (Room.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (Room.Здание Set end)

                // *** End programmer edit section *** (Room.Здание Set end)
            }
        }
    }
}
