//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Здание CustomAttributes)

    // *** End programmer edit section *** (Здание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданиеE", new string[] {
            "Адрес as \'Адрес\'"})]
    [View("ЗданиеL", new string[] {
            "Адрес as \'Адрес\'"})]
    public class Здание : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Здание CustomMembers)

        // *** End programmer edit section *** (Здание CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Адрес CustomAttributes)

        // *** End programmer edit section *** (Здание.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Адрес Get start)

                // *** End programmer edit section *** (Здание.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Здание.Адрес Get end)

                // *** End programmer edit section *** (Здание.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Адрес Set start)

                // *** End programmer edit section *** (Здание.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Здание.Адрес Set end)

                // *** End programmer edit section *** (Здание.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.Test2.Здание));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.Test2.Здание));
                }
            }
        }
    }
}
